name: Java Café - Integração Contínua

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar o JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin' # Uma distribuição popular e gratuita do OpenJDK
          cache: 'maven' # Faz cache das dependências do Maven para acelerar builds futuros
      - name: Compilar e testar com Maven
        run: mvn -B verify --file pom.xml


      - name: Upload do artefato do build
        if: success() # Só executa se os passos anteriores tiverem sucesso
        uses: actions/upload-artifact@v4
        with:
          name: java-cafe-jar # Nome do artefato
          path: target/*.jar # Caminho para o arquivo .jar gerado pelo Maven
